---
title: "Mushroom Yield Stats"
author: "Adrian Wiegman"
date: "April 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(multcompView)
```

## R Markdown

This R markdown evaluates ggplot options for random data reflectig a block design with six treatment groups in each block. In this markdown I also build a function to plot resuls from a tukey honest significant difference post hoc test. 


```{r}
# Define Functions------------------------------------
#######################################################
#FUNCTION: AOVtest
# function to conduct Analysis of Variance, produce a vector of outputs and plot a graph
#inputs:
#y - continuous response variable
#x - categorical x variable
#alpha - significance level e.g. 0.05 or 0.01 or 0.001
#postHoc - T/F if TRUE function runs TukeyHSD
#outputs: returns a list with p value and TukeyHSD results
AOVtest <- function(x=rep(letters[1:3],each=10),
                    y=runif(30)*rep(1:3,each=10),
                    alpha=0.05,
                    postHoc = TRUE){
  if (length(y)!=length(x)){
    stop('x and y vectors are not the same lenght')
  }
  # make sure treatment var, x, a factor
  if (!is.factor(x)){x<-factor(x)}
  df <- data.frame(ID=1:length(y),y=y,x=x)
  test <- aov(y~x, data=df) #analysis of variance function
  pvalue <- as.numeric(unlist(summary(test))[9])
  if (pvalue <= alpha && postHoc == TRUE){
    tuk <- TukeyHSD(test, ordered = FALSE, conf.level = (1 - alpha))
    results <- c('pvalue'= pvalue, #p-value for h0 means are not different
                 'tukey.table'=tuk) #results of tukey table
    return(results)
  }
  results <- c('pvalue'=pvalue, test)
  return(results)
}
#AOVtest()

#######################################################
# FUNCTION: plotAOV
# produces a boxplot labeled with analysis of variance results 
# Inputs: 
# treatment - catagorical x independant variable 
# response - continuous y dependant variable
# statsOnPlot - T/F if TRUE graph p value and post hoc test on plot
# postHoc - T/F if TRUE graph significant difference labels on plot
#Outputs: 
#p - ggplot object with boxplot and results
#Dependancies:
# tukeylabel_df()
# ggplot2
#-----------------------------------------------------------
plotAOV <- function(treatment=rep(1:3,each=10),
                    response=runif(30),
                    statsOnPlot=FALSE,
                    postHoc=FALSE,
                    alpha=0.05){
  #create data frame for analysis
  if(is.integer(treatment)){x <- factor(treatment)
  }else{stop('function failed: treatment must be an integer')}
  df <- data.frame(ID = 1:length(treatment),
                   x=x, #converting to numeric factor
                   y=response)
  
  if(statsOnPlot==TRUE){
    #generate significant diference labels for postHOC tests
    if (postHoc == TRUE){
      stats <- tukeyLabels(treatment=treatment,response=response)
      p <- ggplot(data=df,aes(x=x,y=y))+geom_boxplot()+ 
           geom_text(data=stats, 
                     aes(x=plot.labels,
                         y=V1,
                         label=labels,
                         hjust=c(2,2,2),
                         fontface='bold'))
    } else {
      t <- unlist(summary(aov(y~x,data=df)))
      pvalue <- toString(t[9]) 
      p <- ggplot(data=df,aes(x=x,y=y,fill=x))+
        geom_boxplot()+
        geom_text(aes(x=Inf,y=Inf,hjust=1.1,
                      vjust=1.5,label=paste("p =",pvalue)))
    } #end if postHoc
  } else {#if stats on plot not equal TRUE
  p <- ggplot(data=df,aes(x=x,y=y,fill=x))+geom_boxplot()
  } #end if stats on plot
  return(p) # return ggplot object
}
#plotAOV(statsOnPlot=TRUE,postHoc=TRUE)


#########################
#FUNCTION: tukeylabel_df
#generates labels indicating significant differences from tukey post-hoc
#for use in ggplot2 boxplots
#inputs: 
#x and y - vectors of same length, 
#alpha - a numeric value indicating significance level (e.g. 0.05)
#outputs: a dataframe of labels for the tukey test
#------------------------------------------------
tukeyLabels <- function(treatment=rep(1:3,each=10), # treatment levels
                        response=runif(30), # responses to treatments
                        alpha=0.05){
  # Extract labels and factor levels from Tukey post-hoc
  if(is.factor(treatment)){}else{treatment <- factor(treatment)}
  df <- data.frame(x=treatment,y=response)
  HSD <- TukeyHSD(aov(y~x,data=df), 
                  ordered = FALSE, 
                  conf.level = (1-alpha))
  Tukey.levels <- HSD[['x']][,4]
  Tukey.labels <- multcompLetters(Tukey.levels)['Letters']
  plot.labels <- names(Tukey.labels[['Letters']])
  # Get highest quantile for Tukey's 5 number summary and add a bit of space to buffer between    
  # upper quantile and label placement
  boxplot.df <- plyr::ddply(df, 'x', function (z) max(fivenum(z$y)) + 0.2)
  
  # Create a data frame out of the factor levels and Tukey's homogenous group letters
  plot.levels <- data.frame(plot.labels, 
                            labels = Tukey.labels[['Letters']],
                            stringsAsFactors = FALSE)
  
  # Merge it with the labels
  labels.df <- merge(plot.levels, 
                     boxplot.df, 
                     by.x = 'plot.labels', 
                     by.y = 'x',
                     sort = FALSE)
  
  return(labels.df)
}
#tukeyLabels()

#########################################################################
#FUNCTION: creatExperiment
# function to simulate random normal data for a specified balanced experimental setup
#inputs: 
# number of factors, blocks, levels, replications in experiment
# sample mean and standard deviation of all samples
# the effect size of blocks, factors, treatments, replications

#outputs:
# a datafram containing random data and treatment factors
#notes on updates:
# - This is a revised version of simulateData, which operated very slowly
# because the function called c() to build vectors within a for loop. This version pre-assigns the mode and length of vectors based on the number of factors, blocks, levels and replications. 
# - The response variable model can now be specified in a string using the same notation as lm() 
#   y~x1+x2 --> y = b0 + b1*x1 + b2*x2 + E
    
#-------------------------------------------------------------------------
makeXdf <- function(nBlocks = 1, #number of study blocks or sites
                    nFactors = 1, #number of treatment factors
                    nLevels = 3, #number of treatment levels for each factor
                    nReps = 10 #number of replications f(b(l(r))))
                      ){
  nTotal <- nFactors*nBlocks*nLevels*nReps
  ID <- vector(mode = "numeric", length = nTotal)
  fact <- vector(mode = "numeric", length = nTotal)
  block <- vector(mode = "numeric", length = nTotal)
  level <- vector(mode = "numeric", length = nTotal)
  rep <- vector(mode = "numeric", length = nTotal)
  response <- vector(mode = "numeric", length = nTotal)
  i <- 0
  for (b in seq(1,nBlocks)){
    for (f in seq(1,nFactors)){
      for (l in seq(1,nLevels)){
        for (r in seq(1,nReps)){
          i <- i + 1
          ID[i] <- i
          fact[i] <- f
          block[i] <- b
          level[i] <- l
          rep[i] <- r
          cat(i,"f",f,"b",b,"l",l,"r",r,"\n")
        }# end o loop
      } # end t loop
    } # end b loop
  } # end f loop
  df <- data.frame(ID=ID,
                   Blk=block,
                   Dgst=fact,
                   Rcp=level,
                   Yld=response)
  return(df)
}


#make a dataframe 
df <- makeXdf(nBlocks = 2, #number of study blocks or sites
              nFactors = 2, #number of treatment factors
              nLevels = 6, #number of treatment levels for each factor
              nReps = 4)

# simulate yield as a function of block(Blk) factor(Dgst) and level(Rcp)onto data
b0 <- 450 # average Yld across all data
b1 <- 0 #
b2 <- 200
b3 <- 30
b4 <- 0
SD <- 100

df$Yld <- with(df, b0 + b1*Blk + b2*Dgst + b3*Rcp + b4*Dgst*Rcp + rnorm(length(df$Yld),0,SD))
df
dfAOV <- data.frame (ID=df$ID,
                     Blk=as.factor(df$Blk),
                     Dgst=as.factor(df$Dgst),
                     Rcp=as.factor(df$Rcp),
                     Yld=df$Yld)

str(dfAOV)

model <- lm(Yld~Blk + Dgst*Rcp,data=dfAOV)
summary(model)


#PLOT DATA
library(ggplot2); theme_set(theme_classic())

myColors <- c('red','green','pink','blue','orange','cyan')
p1 <- ggplot(data=dfAOV, mapping=aes(x=Rcp,y=Yld)) + geom_boxplot(data=dfAOV, mapping=aes(fill=Dgst))
p1 + scale_fill_manual(values=myColors)
p1 + scale_fill_brewer(palette="BuGn")

p2 <- ggplot(data=dfAOV, mapping=aes(x=Dgst,y=Yld)) + geom_boxplot(data=dfAOV, mapping=aes(fill=Rcp))

#color schemes available from color brewer
#http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3
# the website above helps you pick the right colors

#Diverging color schemes (two or three colors equal saturation)
p2 + scale_fill_brewer(palette="Spectral")
p2 + scale_fill_brewer(palette="RdYlGn") 
p2 + scale_fill_brewer(palette="PRGn") #color blind safe

#sequential color schemes (two or three colors equal saturation)
p2 + scale_fill_brewer(palette="YlOrRd")
p2 + scale_fill_brewer(palette="RdPu")
p2 + scale_fill_brewer(palette="BuPu") 
p2 + scale_fill_brewer(palette="Greys")


p1 <- ggplot(data=dfAOV, mapping=aes(x=Rcp,y=Yld)) + geom_boxplot(data=dfAOV, mapping=aes(fill=Dgst))
p1 + scale_fill_brewer(palette="Greys")

p2 <- ggplot(data=dfAOV, mapping=aes(x=Dgst,y=Yld)) + geom_boxplot(data=dfAOV, mapping=aes(fill=Rcp))

#color schemes available from color brewer
#http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3
# the website above helps you pick the right colors
p2 + scale_fill_brewer(palette="BuGn")


# now generate a plot with tukey labels
tuk <- tukeyLabels(treatment=dfAOV$Rcp,
                   response = dfAOV$Yld,
                   alpha = 0.05)
print(tuk)
str(tuk)
tukeyPlot <- ggplot(data=dfAOV, mapping=aes(x=Rcp,y=Yld)) + geom_text(data=tuk, aes(x=plot.labels,
                         y=V1,
                         label=labels,
                         hjust=c(rep(.4)*length(labels)),
                         fontface='bold')) +  scale_fill_brewer(palette="BuGn")

tukeyPlot + geom_boxplot(aes(group=Rcp)) + geom_jitter(width=0.1,height=0)
ggsave(filename="tukeyplot_Rcp-Yld.pdf",
       plot=tukeyPlot,
       device="pdf")

```
