---
title: "segmented"
author: "Adrian Wiegman"
date: "April 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Segmented Line regression 
# https://www.r-bloggers.com/r-for-ecologists-putting-together-a-piecewise-regression/
```{r}
library(TeachingDemos)
char2seed("rotten eggs")

#Global Variables
n <- 15
x <- rnorm(n,20,10)
y <- numeric(n)
theta <- 20 # true threshold x value where slope changes
b0a <- 0 # true y-intercept 
b1a <- 0.5 # true slope for x < theta
b1b <- 2 # true slope for x >= theta 
b0b <- b0a + b1a*theta - b1b*theta # y-intercept for x >= theta
# forces convergence of lines at theta
sd <- 10
# Create first segment
Ma <- "(b0a + b1a*x)*(x<theta)"
Mb <- "(b0b + b1b*x)*(x>=theta)"
E <- "rnorm(n, 0, sd)"
Y <- eval(parse(text=paste(M1,M2,E,sep="+")))
y <- (b0a + b1a*x)*(x<theta) + (b0b + b1b*x)*(x>=theta) + rnorm(n, 0, sd)
plot(x,y, pch=16)
```

from eyeballing the plot we can see that the breakpoint is between 7 and 19.
```{r}
#create a variable to hold integer values of breakpoints
thresh <- x[which(x >= 5 & x <= 20)]
#iteratively search for model with lowest mean squared error
mse <- numeric(length(thresh))
for(i in 1:length(thresh)){
  . <- thresh[i]
  piecewise1 <- lm(y ~ x*(x<.) + x*(x>=.))
  mse[i] <- summary(piecewise1)$sigma
}
str(mse)
library(ggplot2)
plot(x=thresh,y=mse)
```
The break point could easily be 13 or 17
```{r}
. <- breaks[which(mse==min(mse))]
piecewise2 <- lm(y ~ x*(x < .) + x*(x > .))
summary(piecewise2)
```


## Segmented Package
```{r}
library(segmented)
df <- data.frame(x=x,y=y)
#fit.glm<- glm(y~x,weight=x,family=binomial,data=df)
fit.lm <- lm(y~x)
fit.seg <- segmented(fit.lm, seg.Z = ~x, psi=14)
summary(fit.seg)
#plot the segmented model
plot(x,y, pch=16, ylim=c(5,20))
plot(fit.seg, add=T)
#fit.seg <- segmented(fit.glm, seg.Z=~age,psi=25)

#extract parameters
xb = summary.segmented(fit.seg)$psi [1,2]
a0 = fit.seg$coefficients[1]
b0 = fit.seg$coefficients[2] # slope for x < xb (break-point)
b1 = fit.seg$coefficients[3] - b0 # slope for x >= xb (break-point)
#rsq = fit.seg
# y = a0 + b0*x for x < bp
# y = a1 + b1*x for x >= bp
```

